# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('former', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='p_id',
            field=models.CharField(max_length=105, primary_key=True, serialize=False),
        ),
    ]
